Formatter class
practice-enterprise/canvas-discord-bot pull request #14
Opened 2020-11-27 21:58 UTC by DrunkenToast

For #13

2020-11-27 22:06 UTC, xunafay requested changes
combine `.text()` and `.append()` into one function using the optional param. Propagate the optional new line param down in the other functions

2020-11-27 22:12 UTC, xunafay commented on src/formatter.ts
> +  return val.replace(/`/g, '\\`').replace(/\*/g, '\\*');
also escape strike through, spoiler and underline
slightly more complicated as `__test__test2__` has to become `\__test\__test2__` aka only one in the pair has to be escaped

2020-11-27 22:48 UTC, xunafay submitted a review, later dismissed

2020-11-29 10:28 UTC, xunafay requested changes

2020-11-29 10:28 UTC, xunafay commented on src/formatter.ts
> +
remove empty newline

2020-11-29 10:28 UTC, xunafay commented on src/formatter.ts
> +  //https://regex101.com/r/o5VvwW/3
remove outdated/unnecessary link

2020-11-29 10:28 UTC, xunafay commented on src/formatter.ts
> +
remove empty newline

2020-11-29 10:28 UTC, xunafay commented on src/formatter.ts
> +*/
add as JSDoc to class

2020-11-29 10:28 UTC, xunafay commented on src/formatter.ts
> +    this.body = append ? `${this.body}${val}\n` : `${this.body}${val}`;
rename append to `nl` in order to keep consistency between functions

2020-11-29 11:39 UTC, xunafay approved these changes

2020-11-29 11:39 UTC, xunafay commented on src/discord.ts
> +import { Formatter } from './formatter';
unused import

2020-11-30 00:34 UTC, PandaGamersHDNL approved these changes

2020-11-30 00:36 UTC, merged