Announcements
practice-enterprise/canvas-discord-bot pull request #45
Opened 2021-03-18 21:58 UTC by DrunkenToast

#44

2021-03-29 12:00 UTC, PandaGamersHDNL submitted a review, later dismissed

2021-03-29 12:16 UTC, xunafay approved these changes, later dismissed

2021-03-29 12:16 UTC, xunafay commented on src/discord.ts
> +      if (!(msg.member?.roles.cache.has(evalRole))) {
add check if in dev environment
`process.env.NODE_ENV == 'development'`

2021-03-29 12:26 UTC, xunafay requested changes

2021-03-29 12:26 UTC, xunafay commented on src/discord.ts
> +        msg.channel.send('you are not in a development enviroment');
You'll need to `return;` to exit the function otherwise execution will continue
I wouldn't send a message but just ignore the command

2021-04-02 11:53 UTC, xunafay approved these changes

2021-04-02 12:12 UTC, PandaGamersHDNL approved these changes

2021-04-02 12:13 UTC, merged