auto role creation over socket
practice-enterprise/canvas-discord-bot pull request #52
Opened 2021-04-09 01:44 UTC by PandaGamersHDNL

2021-04-14 21:56 UTC, DrunkenToast approved these changes

2021-04-15 10:25 UTC, xunafay requested changes

2021-04-15 10:25 UTC, xunafay commented on src/models/guild.ts
> +  Roles: Record<string, string>
properties should be camel case

2021-04-15 10:25 UTC, xunafay commented on src/services/role-assignment-service.ts
> +  }
throw errors instead of returning a boolean

2021-04-15 19:26 UTC, xunafay requested changes

2021-04-15 19:26 UTC, xunafay commented on src/services/role-assignment-service.ts
>      const member = await guild.members.fetch({ 'user': data.userID, 'cache': true, 'force': true }).catch((err) => console.log(err))/*cache.get(data.userID)*/;
.fetch does not return undefined/null
no need to check for it if you remove the unnecessary .catch

2021-04-15 20:31 UTC, xunafay approved these changes

2021-04-15 20:36 UTC, merged