Channel creation
practice-enterprise/canvas-discord-bot pull request #53
Opened 2021-04-14 16:42 UTC by PandaGamersHDNL

2021-04-14 21:54 UTC, DrunkenToast approved these changes

2021-04-14 21:54 UTC, DrunkenToast commented on src/models/guild.ts
> +  //Record<courseID, channelID), courseID should be number -> parseInt()
Since we're going to all string for courseIDs you can change it to just //Record<courseID, channelID)

2021-04-14 21:54 UTC, DrunkenToast commented on src/services/channel-creation-service.ts
> +
remove \n

2021-04-14 21:54 UTC, DrunkenToast commented on src/services/channel-creation-service.ts
> +    if (!await client.channels.fetch(data.courseChannels.CategoryID).catch(() => undefined)) {
`.then(() => true).catch(() => false)` perhaps for readability

2021-04-14 21:54 UTC, DrunkenToast commented on src/services/channel-creation-service.ts
> +      categoryChannel != undefined ? data.courseChannels.CategoryID = categoryChannel.id : categoryChannel = undefined;
Might want an if/else for readability

2021-04-15 10:30 UTC, xunafay requested changes

2021-04-15 10:30 UTC, xunafay commented on src/models/guild.ts
> +  CategoryID: string,
properties should be camel case

2021-04-15 10:30 UTC, xunafay commented on src/services/channel-creation-service.ts
> +        channel != undefined ? data.courseChannels.channels[courseID] = channel.id : channel = undefined;
why is this a ternary?
```ts
if (channel) {
  data.courseChannels.channels[courseID] = channel.id
}
```

2021-04-15 10:30 UTC, xunafay commented on src/services/channel-creation-service.ts
> +    CategoryID: string,
properties should be camel case

2021-04-15 10:30 UTC, xunafay commented on src/services/channel-creation-service.ts
> +    CategoryID: string,
also move models to the models folder

2021-04-15 20:34 UTC, xunafay approved these changes

2021-04-15 20:38 UTC, merged