Feat: prevent exceeding character limit in string and embed messages
practice-enterprise/canvas-discord-bot pull request #61
Opened 2021-04-21 22:57 UTC by DrunkenToast

Prevent sending messages that are too long by cutting them off.
Following official character limits of discords:
- 2000 chars for string msg
- these requirements for embeds https://discord.com/developers/docs/resources/channel#embed-limits

2021-04-21 23:00 UTC, DrunkenToast commented on src/discord.ts
> +        msg.channel.send(response, {split: true});
Depending on what we prefer we may want to either split the message, or simply cut it off.
1. wall of text (over 2000 chars)
2. lost info

2021-05-08 14:37 UTC, xunafay requested changes

2021-05-08 14:37 UTC, xunafay commented on src/commands.ts
> +    async response(msg: Message, guildConfig: GuildConfig): Promise<Response | void> {
remove testing data

2021-05-08 19:35 UTC, xunafay approved these changes

2021-05-09 15:16 UTC, PandaGamersHDNL approved these changes

2021-05-14 17:09 UTC, merged