Fix notes
practice-enterprise/canvas-discord-bot pull request #68
Opened 2021-05-05 21:31 UTC by DrunkenToast

Make it work in DMs, weird get inconsistenties etc

2021-05-08 14:36 UTC, xunafay requested changes
move notes logic in `command.ts` into seperate file

2021-05-08 15:21 UTC, DrunkenToast commented
> 
> 
> move notes logic in `command.ts` into seperate file

Done, ready for review.

2021-05-08 16:34 UTC, PandaGamersHDNL requested changes

2021-05-08 16:34 UTC, PandaGamersHDNL commented on src/services/notes-service.ts
> +      console.log('start');
Rm log

2021-05-08 16:34 UTC, PandaGamersHDNL commented on src/services/notes-service.ts
> +      console.log('here');
Rm log

2021-05-08 16:34 UTC, PandaGamersHDNL commented on src/services/notes-service.ts
> +    console.log(notes);
Rm log

2021-05-09 15:05 UTC, xunafay approved these changes

2021-05-09 15:13 UTC, PandaGamersHDNL approved these changes

2021-05-09 15:13 UTC, merged