Prettify responses and usage of commands
practice-enterprise/canvas-discord-bot pull request #69
Opened 2021-05-08 14:23 UTC by DrunkenToast

Can create simple embeds but also extra help for commands and lists.
Closes #32

2021-05-09 17:15 UTC, PandaGamersHDNL approved these changes

2021-05-10 12:18 UTC, xunafay requested changes

2021-05-10 12:18 UTC, xunafay commented on src/commands.ts
> +  }
remove test data

2021-05-10 12:18 UTC, xunafay commented on src/util/embed-builder.ts
> +export enum colors {
use PascalCase for types, classes and enums

2021-05-10 12:18 UTC, xunafay commented on src/util/embed-builder.ts
> +type Color = 'info' | 'success' | 'warning' | 'error' | 'gray' | 'discord' | 'canvas';
is this type still used?

2021-05-10 16:33 UTC, xunafay approved these changes

2021-05-10 17:08 UTC, merged